version: "3.8"

services:
   account_db:
      image: postgres:14
      environment:
          - POSTGRES_USER=account
          - POSTGRES_PASSWORD=account@123
          - POSTGRES_DB=account_service
      ports:
          - "5438:5432"
      volumes:
          - data:/var/lib/postgresql/data 
 
   pg-admin:
      image: dpage/pgadmin4:6
      environment:
          - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
          - PGADMIN_DEFAULT_PASSWORD=admin@123
          - PGADMIN_LISTEN_PORT=5050
      ports:
          - "5050:5050"

   account_service:
      image: account_service
      ports:
          - "8080:8080"

volumes:
  data: