version: "3.8"

services: 
   rabbit:                  
      image: rabbitmq:3.12-management
      container_name: rabbitmq
      hostname: rabbitmq
      healthcheck:
         test: rabbitmq-diagnostics check_port_connectivity
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports:
         - "5672:5672"
         - "15672:15672"
      extends: 
         file: common.yml
         service: ms-deploy-network

   configserver:
      image: vicheakbank/configserver:v2
      container_name: configserver
      healthcheck:
         test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports:
         - "8071:8071"
      depends_on:
         rabbit: 
            condition: service_healthy
      extends: 
         file: common.yml
         service: ms-base

   eurekaserver:
      image: vicheakbank/eurekaserver:v2
      container_name: eurekaserver
      healthcheck:
         test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports:
         - "9000:9000"
      environment:
         EUREKA_INSTANCE_HOSTNAME: eurekaserver
      extends: 
         file: common.yml
         service: ms-base-configserver 

   account_service:
      image: vicheakbank/account:v2
      container_name: account_service
      healthcheck:
         test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports:
         - "8080:8080"
      extends: 
         file: common.yml
         service: ms-base-eurekaserver

   card_service:
      image: vicheakbank/card:v2
      container_name: card_service
      healthcheck:
         test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports:
         - "8070:8070"
      depends_on:
         mongodb:
            condition: service_healthy
      environment:
         MONGODB_HOST_NAME: mongodb
      extends: 
         file: common.yml
         service: ms-base-eurekaserver

   loan_service:
      image: vicheakbank/loan:v2
      container_name: loan_service
      healthcheck:
         test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports:
         - "8090:8090"
      depends_on:
         mongodb:
            condition: service_healthy
      environment:
         MONGODB_HOST_NAME: mongodb
      extends: 
         file: common.yml
         service: ms-base-eurekaserver
      
   gatewayserver:
      image: vicheakbank/gatewayserver:v2
      container_name: gatewayserver
      ports:
         - "8072:8072"
      depends_on:
         account_service:
            condition: service_healthy
         card_service:
            condition: service_healthy
         loan_service:
            condition: service_healthy
      extends: 
         file: common.yml
         service: ms-base-eurekaserver

   mongodb:
      image: mvertes/alpine-mongo:latest
      container_name: mongodb
      healthcheck:
         test: "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      ports: 
         - "7777:27017"
      volumes:
         - './data:/data/db'
      extends: 
         file: common.yml
         service: ms-deploy-network

networks:
   vicheaknetwork: